name: Auto Assign
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6 # v3
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 🚧　Install
        run: |
          yarn
      - name: 📦　Build
        run: |
          yarn build
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          addReviewers: true
          addAssignees: true
          numberOfReviewers: 1
          numberOfAssignees: 1
          reviewers: |
            amanstep
          assignees: |
            amanstep
          skipKeywords: wip
          excludeLabels: dependencies, wip
